### ISSUE TITLE
IP addresses for DMgr and Nodes

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#10]
@majguo @edburns Can you please investigate this.
Currently all VMs have public IP. From security perspective, we should have:
- DMgr with public IP, and access to this VM should be allowed on selected ports
- Nodes with private IPs.

**Comment by majguo** [comment]
@git4rk OK. Let's track this issue in a separate PR, instead of the existing PR #9.
