### ISSUE TITLE
Get the time various stages take for tWAS ND cluster deployment

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#105]
The deployment time includes:
- setup VM
- update tWAS
- created profile
- setup cluster
- configure IHS
- ...

**Comment by majguo** [comment]
For one deployment consisting of 1 dmgr, 1 worker node and 1 IHS, the time taken for different stages is as below:
- setup VMs: ~2 mins, 40 secs
- update tWAS & IHS (including entitlement check): ~5 mins, 10 secs  
- created profile (both dmgr and custom profiles, including the time that worker node waits for dmgr server ready): ~10 mins, 43 secs
- setup cluster: ~ 28 secs
- configure IHS (only time of IHS configuration on dmgr is counted in, time of IHS configuration on IHS vm is ignored as the duration is covered in other deployment stage): ~2 mins, 37 secs

The PR including code changes which are capable of generating timestamps in deployments/logs will be opened soon.

**Comment by git4rk** [comment]
Thanks @majguo I am surprised to see that create profile takes almost 11 minutes. That probably should be investigated.
