### ISSUE TITLE
Update pom.xml with official VM base image

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#11]
Reference: https://github.com/WASdev/azure.websphere-traditional.cluster/pull/9/files#r623571309

- Update pom.xml with official VM base image once it is published
- For future, is it possible to pass this information dynamically, so that we do not have to update and publish this code, just to change the image id.

**Comment by majguo** [comment]
So far we only have one VM base image, so I think current implementation is good enough. 
Once we have multiple VM image versions, we can parameterize the image reference in `createUiDefinition.json` so that user can choose the version they want to deploy.
