### ISSUE TITLE
./im_installer/userinstc: Permission denied

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#125]
When I tested to deploy VMs for `twas-nd` and `ihs` which are used for generating disk SAS URLs, the deployment failed with the following fatal error: 

```
install.sh: line 55: ./im_installer/userinstc: Permission denied
```

It needs to be resolved before updating the ND and IHS images to 9.0.5.10 (issue #122).

**Comment by git4rk** [comment]
@majguo There is a regression in the IM packaging. The issue has been reported to the IM team. 
Please add `chmod -R 755 *` to the script after unzipping IM files to workaround the issue.
