### ISSUE TITLE
GitHub Actions hygiene 2021-12

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#130]
- Ensure all actions are invocable with `repository_dispatch`.
- Ensure all actions have sufficiently distinct `types` so that they only run when desired.
- Ensure all actions that run integration tests have `integration-test-all` type.

**Comment by edburns** [comment]
Please add these labels:
* liberty.aro
* liberty.aks
* twas-image

**Comment by majguo** [comment]
Hello @edburns The recommended changes were applied to all related repos:
* https://github.com/WASdev/azure.liberty.aks/pull/14
* https://github.com/WASdev/azure.liberty.aro/pull/37
* https://github.com/WASdev/azure.websphere-traditional.cluster/pull/119
* https://github.com/WASdev/azure.websphere-traditional.singleserver/pull/7/commits/fbf20fd5a3741ccc4ab3dd5a89bcb2e53cb14ebd
* https://github.com/WASdev/azure.websphere-traditional.image/pull/55

Pls close the issue, thanks.
