### ISSUE TITLE
Cross-repo: UI wording changes

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#135]
For all of our offers that have Azure Portal UI, ensure the following is true

- Use `IBMid` never `IBM ID`.
- Change **please report them here** to **open an issue** or **open an Azure issue**.
- Change **file an issue** to **open an issue**.

Cc: @helyarp .

**Comment by edburns** [comment]
@git4rk  please apply the following labels to this issue.

- liberty.aks
- liberty.aro
- twas-singleserver

**Comment by git4rk** [comment]
@edburns done.

**Comment by majguo** [comment]
Hello @edburns The recommended changes were applied to all related repos:
* https://github.com/WASdev/azure.liberty.aks/pull/24
* https://github.com/WASdev/azure.liberty.aro/pull/51
* https://github.com/WASdev/azure.websphere-traditional.cluster/pull/136
* https://github.com/WASdev/azure.websphere-traditional.singleserver/pull/16

Pls close the issue, thanks.
