### ISSUE TITLE
Creating a custom profile and federating the profile into the deployment manager cell doesn't work in tWAS 9.0.5.11

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#151]
## Problem overview

As the twas image was upgraded to **9.0.5.11**, the twas-cluster solution offer is also being updated to reference twas image **9.0.5.11** (details pls see #137). However, based on @git4rk 's initial testing for the twas-cluster-offer [preview link](https://portal.azure.com/#create/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.2021-04-08-twas-cluster-previewcluster) and my follow-up testing, the deployment failed due to creating a custom profile and federating the profile into the deployment manager cell doesn't work in tWAS **9.0.5.11** any longer. However, the deployment works as expected for the solution offer with tWAS **9.0.5.10**.

## Problem triage

The [following command](https://github.com/WASdev/azure.websphere-traditional.cluster/blob/main/src/main/scripts/install.sh#L210-L212) used for creating a custom profile and federating the profile into the deployment manager cell doesn't work in tWAS **9.0.5.11**:

```
${WAS_ND_INSTALL_DIRECTORY}/bin/manageprofiles.sh -create -profileName $profileName -hostName $hostName -nodeName $nodeName \
        -profilePath ${WAS_ND_INSTALL_DIRECTORY}/profiles/$profileName -templatePath ${WAS_ND_INSTALL_DIRECTORY}/profileTemplates/managed \
        -dmgrHost $dmgrHostName -dmgrPort $dmgrPort -dmgrAdminUserName $dmgrAdminUserName -dmgrAdminPassword $dmgrAdminPassword
```

Error message:
```
The following validation errors were present with the command line arguments:
        dmgrHost: Unable to connect to the deployment manager on the specified hostname and port.
```

Version info:
```
${WAS_ND_INSTALL_DIRECTORY}/bin/versionInfo.sh

WVER0010I: Copyright (c) IBM Corporation 2002, 2012; All rights reserved.
WVER0012I: VersionInfo reporter version 1.15.1.48, dated 2/8/12

--------------------------------------------------------------------------------
IBM WebSphere Product Installation Status Report
--------------------------------------------------------------------------------

Report at date and time March 22, 2022 5:05:17 AM UTC

Installation
--------------------------------------------------------------------------------
Product Directory        /datadrive/IBM/WebSphere/ND/V9
Version Directory        /datadrive/IBM/WebSphere/ND/V9/properties/version
DTD Directory            /datadrive/IBM/WebSphere/ND/V9/properties/version/dtd
Log Directory            /root/var/ibm/InstallationManager/logs

Product List
--------------------------------------------------------------------------------
ND                       installed


JAVA8                    installed

Installed Product
--------------------------------------------------------------------------------
Name                  IBM WebSphere Application Server Network Deployment
Version               9.0.5.11
ID                    ND
Build Level           f5112208.01
Build Date            2/22/22
Package               com.ibm.websphere.ND.v90_9.0.5011.20220222_1524
Architecture          x86-64 (64 bit)
Installed Features    WebSphere Application Server traditional
                      EJBDeploy tool for pre-EJB 3.0 modules
                      Embeddable EJB container
                      Stand-alone thin clients and resource adapters

Installed Product
--------------------------------------------------------------------------------
Name            IBM SDK, Java Technology Edition, Version 8
Version         8.0.7.5
ID              JAVA8
Build Level     pxa6480sr7fp5-20220208_01
Build Date      02/08/22
Architecture    x86-64 (64 bit)

--------------------------------------------------------------------------------
End Installation Status Report
--------------------------------------------------------------------------------
```

### The same command works for tWAS 9.0.5.10

However, it's verified that the same command executes successfully in tWAS 9.0.5.10, here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewwasndt91-n-cluster) deployed with tWAS 9.0.5.10 for testing. 

Version info:
```
${WAS_ND_INSTALL_DIRECTORY}/bin/versionInfo.sh
WVER0010I: Copyright (c) IBM Corporation 2002, 2012; All rights reserved.
WVER0012I: VersionInfo reporter version 1.15.1.48, dated 2/8/12

--------------------------------------------------------------------------------
IBM WebSphere Product Installation Status Report
--------------------------------------------------------------------------------

Report at date and time March 22, 2022 5:05:33 AM UTC

Installation
--------------------------------------------------------------------------------
Product Directory        /datadrive/IBM/WebSphere/ND/V9
Version Directory        /datadrive/IBM/WebSphere/ND/V9/properties/version
DTD Directory            /datadrive/IBM/WebSphere/ND/V9/properties/version/dtd
Log Directory            /root/var/ibm/InstallationManager/logs

Product List
--------------------------------------------------------------------------------
ND                       installed
JAVA8                    installed

Installed Product
--------------------------------------------------------------------------------
Name                  IBM WebSphere Application Server Network Deployment
Version               9.0.5.10
ID                    ND
Build Level           f5102145.01
Build Date            11/8/21
Package               com.ibm.websphere.ND.v90_9.0.5010.20211108_1200
Architecture          x86-64 (64 bit)
Installed Features    WebSphere Application Server traditional
                      EJBDeploy tool for pre-EJB 3.0 modules
                      Embeddable EJB container
                      Stand-alone thin clients and resource adapters

Installed Product
--------------------------------------------------------------------------------
Name            IBM SDK, Java Technology Edition, Version 8
Version         8.0.7.0
ID              JAVA8
Build Level     pxa6480sr7-20211025_01
Build Date      10/25/21
Architecture    x86-64 (64 bit)

--------------------------------------------------------------------------------
End Installation Status Report
--------------------------------------------------------------------------------
```

### Workaround

Refer to [PK47562: PROFILE CREATION TOOL FAILS VALIDATING -DMGRHOST AND -DMGRPORT PARAMETERS](https://www.ibm.com/support/pages/apar/PK47562) to workaround the problem, the command can be divided into two steps: 
* First create the managed profile,
* and then use the addNode command line tool to add the profile to a deployment manager's cell

```
# Create a custom profile
${WAS_ND_INSTALL_DIRECTORY}/bin/manageprofiles.sh -create -profileName $profileName -hostName $hostName -nodeName $nodeName \
        -profilePath ${WAS_ND_INSTALL_DIRECTORY}/profiles/$profileName -templatePath ${WAS_ND_INSTALL_DIRECTORY}/profileTemplates/managed

# Federate the custom profile into the deployment manager cell
${WAS_ND_INSTALL_DIRECTORY}/profiles/$profileName/bin/addNode.sh $dmgrHostName $dmgrPort -username $dmgrAdminUserName -password $dmgrAdminPassword
```

I tested and the workaround did work.

## Conclusion

The problem looks like a regression introduced in tWAS **9.0.5.11**. As a result, the issue is to request the further investigation on why the command used for creating a custom profile and federating the profile into the deployment manager cell doesn't work in tWAS **9.0.5.11**, and the fix accordingly.

**Comment by majguo** [comment]
I tested the following 4 use cases, which support my triage result above:
1. deploy with tWAS 9.0.5.11 + trial license:
    * no package upgrade
    * failed due to the issue documented in [# 151](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/151)
1. deploy with tWAS 9.0.5.11 + entitled IBM id:
    * executed the package upgrade operation but no newer version installed as 9.0.5.11 is the latest one available now
    * failed with the same issue in [# 151](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/151)
1. deploy with tWAS 9.0.5.10 + trial license:
    * no package upgrade
    * **Succeeded**
1. deploy with tWAS 9.0.5.10 + entitled IBM id:
    * executed the package upgrade operation and newer version 9.0.5.11 is installed
    * failed with the same issue in [# 151](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/151)

**Comment by majguo** [comment]
Some references:
* [manageprofiles command](https://www.ibm.com/docs/en/was-nd/9.0.5?topic=mpdios-manageprofiles-command)
* [addNode command](https://www.ibm.com/docs/en/was-nd/9.0.5?topic=tools-addnode-command)
* [IBM WebSphere - Add (federate) a node into network deployment manager (addNode)](http://www.freekb.net/Article?id=1544)
* [PK47562: PROFILE CREATION TOOL FAILS VALIDATING -DMGRHOST AND -DMGRPORT PARAMETERS](https://www.ibm.com/support/pages/apar/PK47562)

**Comment by git4rk** [comment]
Related APAR: https://www.ibm.com/support/pages/apar/PH44602

**Comment by majguo** [comment]
Related fix in WAS: [PH44602:NullPointerException in WebSphere socket factory in 8.5.5.21 and 9.0.5.11](https://www.ibm.com/support/pages/node/6565721)

**Comment by majguo** [comment]
Fix is published, tested and verified, closing the issue now.
