### ISSUE TITLE
Failed to install IHS 9.0.5.11

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#154]
## Problem description

In order to upgrade IHS base image to 9.0.5.11, a VM needs to be provisioned and installed with **IHS 9.0.5.11**. However, I observed that IHS failed to be installed due to the following errors:
```
ERROR: Failed to find required installation files.
  CRIMA1161E ERROR: Failed to find required installation files.

  Explanation: Installation Manager did not find required installation files from the repository. An issue has occurred with the package that cannot be resolved by Installation Manager.

  User Action: If the repository files were transferred from a different location before the installation, verify that the files were not altered during the transfer operation. Copy the repository files to a different location and install from that location. If the repository files were not transferred note the package name and version number and contact customer support.
    ERROR: 'plug-in com.ibm.ihs.panel.v90_9.0.0.20160317_0000' not found.
    ERROR: 'plug-in com.ibm.was.ihs.moreinfo.v90_9.0.0.20151008_0000' not found.
```

## How to reproduce

Follow steps below to reproduce the issue:
```
IM_INSTALL_DIRECTORY=<PATH_TO_IM_INSTALL_DIRECTORY>
IM_SHARED_DIRECTORY=<PATH_TO_IM_SHARED_DIRECTORY>
REPOSITORY_URL=https://www.ibm.com/software/repositorymanager/entitled
IBM_HTTP_SERVER=com.ibm.websphere.IHS.v90
WEBSPHERE_PLUGIN=com.ibm.websphere.PLG.v90
WEBSPHERE_WCT=com.ibm.websphere.WCT.v90
IBM_JAVA_SDK=com.ibm.java.jdk.v8
IHS_INSTALL_DIRECTORY=<PATH_TO_IHS_INSTALL_DIRECTORY>
PLUGIN_INSTALL_DIRECTORY=<PATH_TO_PLUGIN_INSTALL_DIRECTORY>
WCT_INSTALL_DIRECTORY=<PATH_TO_WCT_INSTALL_DIRECTORY>
SSL_PREF="com.ibm.cic.common.core.preferences.ssl.nonsecureMode=false"
DOWNLOAD_PREF="com.ibm.cic.common.core.preferences.preserveDownloadedArtifacts=false"

# Save credentials to a secure storage file
${IM_INSTALL_DIRECTORY}/eclipse/tools/imutilsc saveCredential -secureStorageFile storage_file \
    -userName <entitled-ibm-id> -userPassword <entitled-ibm-id-pwd> -passportAdvantage

# Install IBM HTTP Server V9 using IBM Installation Manager
${IM_INSTALL_DIRECTORY}/eclipse/tools/imcl install "$IBM_HTTP_SERVER" "$IBM_JAVA_SDK" -repositories "$REPOSITORY_URL" \
    -installationDirectory ${IHS_INSTALL_DIRECTORY}/ -sharedResourcesDirectory ${IM_SHARED_DIRECTORY}/ \
    -secureStorageFile storage_file -acceptLicense -installFixes recommended -preferences $SSL_PREF,$DOWNLOAD_PREF -showProgress
```

## Additional info

However, pls **NOTICE** that IHS plugin and WCT can be **successfully** installed:
```
# Install Web Server Plug-ins V9 for IBM WebSphere Application Server using IBM Installation Manager
${IM_INSTALL_DIRECTORY}/eclipse/tools/imcl install "$WEBSPHERE_PLUGIN" "$IBM_JAVA_SDK" -repositories "$REPOSITORY_URL" \
    -installationDirectory ${PLUGIN_INSTALL_DIRECTORY}/ -sharedResourcesDirectory ${IM_SHARED_DIRECTORY}/ \
    -secureStorageFile storage_file -acceptLicense -installFixes recommended -preferences $SSL_PREF,$DOWNLOAD_PREF -showProgress

# Install WebSphere Customization Toolbox V9 using IBM Installation Manager
${IM_INSTALL_DIRECTORY}/eclipse/tools/imcl install "$WEBSPHERE_WCT" "$IBM_JAVA_SDK" -repositories "$REPOSITORY_URL" \
    -installationDirectory ${WCT_INSTALL_DIRECTORY}/ -sharedResourcesDirectory ${IM_SHARED_DIRECTORY}/ \
    -secureStorageFile storage_file -acceptLicense -installFixes recommended -preferences $SSL_PREF,$DOWNLOAD_PREF -showProgress
```

Output:
```
                 25%                50%                75%                100%
------------------|------------------|------------------|------------------|
............................................................................
Installed com.ibm.websphere.PLG.v90_9.0.5011.20220222_1524 to the /datadrive/IBM/WebSphere/Plugins/V9/ directory.
Installed com.ibm.java.jdk.v8_8.0.7005.20220308_0733 to the /datadrive/IBM/WebSphere/Plugins/V9/ directory.
                 25%                50%                75%                100%
------------------|------------------|------------------|------------------|
............................................................................
Installed com.ibm.websphere.WCT.v90_9.0.5011.20220222_1524 to the /datadrive/IBM/WebSphere/Toolbox/V9/ directory.
Installed com.ibm.java.jdk.v8_8.0.7005.20220308_0733 to the /datadrive/IBM/WebSphere/Toolbox/V9/ directory.
```

## Summary

To wary up, the issue needs to be further investigated by WAS team. @edburns @git4rk @gcharters .

**Comment by git4rk** [comment]
@majguo WAS support would like some logs after `imcl install` fails, using this command: `imcl exportinstalldata imagent.zip`. Can you please generate and send that.

**Comment by majguo** [comment]
@git4rk Here it is: [imagent.zip](https://github.com/WASdev/azure.websphere-traditional.cluster/files/8355083/imagent.zip)

**Comment by git4rk** [comment]
@majguo WAS Support is unable to recreate the issue. They have asked to try two things (one at a time):
1. use -cPA  instead of -repositories url
2. use -masterPasswordFile in addition to -secureStorageFile

**Comment by git4rk** [comment]
@majguo I tried the steps WAS support provided ^^. It is still failing. I will continue to work with them.

**Comment by git4rk** [comment]
I tried few things, along with using two different IBM Ids. Install failed for ID1 but worked for ID2. Here are my findings:
1. Using `-cPA` or `-repositories https://www.ibm.com/software/repositorymanager/entitled` for `imcl install` does not make any difference.
2. Using `-masterPasswordFile` does not make any difference.
3. `imcl listAvailablePackages` output is slightly different for both IDs.
    1. Both Ids have this list for 9.0.5.11:
 ```
com.ibm.websphere.APPCLIENT.v90_9.0.5011.20220222_1524
com.ibm.websphere.BASE.v90_9.0.5011.20220222_1524
com.ibm.websphere.EDGECP.v90_9.0.5011.20220223_2223
com.ibm.websphere.EDGELBIPV4IPV6.v90_9.0.5011.20220223_2249
com.ibm.websphere.IHS.v90_9.0.5011.20220222_1524
com.ibm.websphere.IHS.zOS.v90_9.0.5011.20220222_1532
com.ibm.websphere.ILAN.v90_9.0.5011.20220222_1524
com.ibm.websphere.ND.v90_9.0.5011.20220222_1524
com.ibm.websphere.NDDMZ.v90_9.0.5011.20220222_1524
com.ibm.websphere.PLG.v90_9.0.5011.20220222_1524
com.ibm.websphere.WCT.v90_9.0.5011.20220222_1524
```
    2. ID2 (for which install worked) also had these two additional pkgs (not sure if that makes a difference):
```
com.ibm.websphere.PLG.zOS.v90_9.0.5011.20220222_1532
com.ibm.websphere.zOS.v90_9.0.5011.20220222_1529
```

If it is entitlement issue then it is weird that the ID1 can still install WAS ND 9.0.5.11, but can not install IHS 9.0.5.11 (which used to work before, at least until 9.0.5.10).

**Comment by git4rk** [comment]
- There seems to be some issue with `https://www.ibm.com/software/repositorymanager/entitled` repo.
- If I use this repo (on the VM): `https://www.ibm.com/software/repositorymanager/com.ibm.websphere.IHS.v90,https://www.ibm.com/software/repositorymanager/com.ibm.java.jdk.v8` or  `http://www.ibm.com/software/repositorymanager/V9WASND` then the install works.
- It might take some time resolve the */entitled repo issue. I suggest that we use `http://www.ibm.com/software/repositorymanager/V9WASND` as repo URL.

- I created a new branch and changed the REPOSITORY_URL:
https://github.com/WASdev/azure.websphere-traditional.image/blob/rk-repo-url-154/ihs/src/main/scripts/virtualimage.properties
- Then I ran the ihs CI/CD using this branch, but it is still using */entitled repo

@majguo 
1. Do you know why is the [ihs CI/CD](https://github.com/WASdev/azure.websphere-traditional.image/runs/5741115610?check_suite_focus=true) did not pick up my changes even if I used my branch to kickoff the Workflow?
2. Feel free to make the change, try it out and create a PR.

**Comment by majguo** [comment]
> 1. Do you know why is the [ihs CI/CD](https://github.com/WASdev/azure.websphere-traditional.image/runs/5741115610?check_suite_focus=true) did not pick up my changes even if I used my branch to kickoff the Workflow?
> 2. Feel free to make the change, try it out and create a PR.

@git4rk See https://github.com/WASdev/azure.websphere-traditional.image/pull/61 which addressed your question/request above. Once it's merged, the CICD pipeline should pick up changes from the branch you specified when kicking off the Workflow from the UI.
