### ISSUE TITLE
Create GitHub Action secrets needed to run new added pipeline `integration-test`

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#176]
Hello @git4rk The following GitHub Action secrets are needed to run new added pipeline `integration-test`

* AZURE_CREDENTIALS
  * Use the same value of secret `AZURE_CREDENTIALS` defined in [WASdev/azure.websphere-traditional.singleserver](https://github.com/WASdev/azure.websphere-traditional.singleserver)
* USER_NAME
  * Use `WASdev`
* VM_ADMIN_ID
  * The username used for the VM and websphere console, pls define by yourself
* VM_ADMIN_PASSWORD
  * The password used for the VM and websphere console, pls define by yourself
* MSTEAMS_WEBHOOK
  * Use the same value of secret `MSTEAMS_WEBHOOK` defined in [WASdev/azure.websphere-traditional.singleserver](https://github.com/WASdev/azure.websphere-traditional.singleserver)

Reference the following issue for more information:
* WASdev/azure.websphere-traditional.singleserver/issues/44

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue once you add the required secrets.

**Comment by git4rk** [comment]
Added required secrets and ran integration test workflow successfully.
