### ISSUE TITLE
Create GitHub Action secret needed to enable IBM DB2 database connection in the existing `integration-test` pipeline

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#178]
Hello @git4rk The following GitHub Action secret is needed to **enable Db2 support** in the existing pipeline `integration-test`:

* DB2INST1_PASSWORD
  *  Specify the respective Db2 Instance Password. See **Advanced Configuration Options** > **DB2INST1_PASSWORD** from [ibmcom/db2 - Docker Image | Docker Hub](https://hub.docker.com/r/ibmcom/db2) for more information.

Reference the following issue for the other GitHub Action secrets required for pipeline `integration-test`:
* #176

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue once you add the required secret.

**Comment by git4rk** [comment]
secret created.
