### ISSUE TITLE
Support Application Gateway

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#191]
UI design for supporting Azure Application Gateway:

## Screenshots

* ![image](https://user-images.githubusercontent.com/10357495/208221306-b9d8b89b-aba1-4060-bee3-84aa58104bcd.png)
* ![image](https://user-images.githubusercontent.com/10357495/207750719-c25876e0-417f-44c1-ab14-fd7ea07508f5.png)

## UI changes summary

* In the renamed **Load balancer** tab:
   * The tab name is changed from **IBM HTTP Server Load Balancer** to **Load balancer**
   * The name of options group is updated to **Select a load balancer**. Its tooltip is also updated accordingly with the new load balancer option **Azure Application Gateway**
   * Use options group to allow user to select a load balancer (Azure Application Gateway / IBM HTTP Server) or not
   * Provide Azure Application Gateway settings for user inputs if user selects to deploy Azure Application Gateway 
* In the **Networking** tab
  * Update the description in the information box if user selects to deploy Azure Application Gateway
  * Added a new subnet for Application Gateway if user selects to deploy Azure Application Gateway

## Preview UI changes 

Reviewer can also preview the UI changes using the Create UI Definition Sandbox:

* Open [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade) in a new tab of browser.
* Open UI source code [createUiDefinition.json](https://raw.githubusercontent.com/majguo/azure.websphere-traditional.cluster/support-app-gw/src/main/arm/createUiDefinition.json) in a new tab of the browser.
* Replace the content of work area in **Create UI Definition Sandbox** with the content of UI source code `createUiDefinition.json`.
* Click Preview at the left-bottom of **Create UI Definition Sandbox**.

**Comment by edburns** [comment]
Hello @majguo 

 I am giving this feedback without having reviewed feedback from other stakeholders. I apologize in advance if others have already given similar feedback.

In the **Select a load balancer** question, change **No** to **None**.

**Comment by majguo** [comment]
Hello @edburns
 
Good catch, thanks for your review. I've updated the screenshot to reflect your feedback.

**Comment by helyarp** [comment]
@majguo Hi, the UI strings look good. A nit: The IBM style is to use present tense (avoid "will"); I'm not sure what MS style suggests. To use present tense, change "This option will provision" to "This option provisions" and "This option will create" to "This option creates". I suppose follow the existing style for similar strings.

**Comment by majguo** [comment]
Hello @helyarp , thanks for your review and suggestion. I went through other strings and they also use future tense, so I won't change them in order to follow the existing style.
