### ISSUE TITLE
Is it possible to expose an option to enable/disable cookie based affinity for IBM HTTP Server?

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#192]
When I'm working on #191, there is an option for user to enable/disable cookie based affinity for Azure Application Gateway. The issue is to raise the similar questions for IBM HTTP Server:
* What is the default value of cookie based affinity for IBM HTTP Server? Enabled or disabled by default?
* Can we simply expose an option in UI for user to enable/disable cookie based affinity for IBM HTTP Server?

**Comment by covener** [comment]
> What is the default value of cookie based affinity for IBM HTTP Server? Enabled or disabled by default?

It may not represent the same exact same behavior, but essentially "enabled".

> Can we simply expose an option in UI for user to enable/disable cookie based affinity for IBM HTTP Server?

It is better not to expose anything here at all.  When IHS is used with WebSphere, IHS performs session affinity based on:
1. The websphere cluster configuration distilled down to plugin-cfg.xml, including the type of affinity to be used per application and the cookie name
2. the cookies it observes at runtime

IHS and WAS will generally have to agree on any change to the details of affinity, so I would not expose anything here.

---

"passive" cookie affinity, where WAS issues a set-cookie and IHS reads cookies from the client to keep affinity, is almost universally used by IHS+WAS and it's enabled by default.
It's possible the AAG option turns on what some servers call "active affinity" where the gateway itself emits cookies to handle affinity.  IHS doesn't have an active affinity option.
