### ISSUE TITLE
Enable Azure Application Gateway in the existing `integration-test` pipeline

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#194]
To select Azure Application Gateway as the load balancer in the existing `integration-test` pipeline, `User Access Administrator` role is required for the service principal specified in GitHub Action secret `AZURE_CREDENTIALS`. Follow steps below to assign `User Access Administrator` role to the related service principal:

1. Find out the service principal specified in GitHub Action secret `AZURE_CREDENTIALS`
1. Write down its `client id`
1. Run the following command to assign `User Access Administrator` role to the service principal
    ```
    clientId=<client-id-of-the-service-principal>
    az role assignment create --assignee ${clientId} --role "User Access Administrator"
    ``` 
1. Run the following command to check if `User Access Administrator` role is successfully assigned to the service principal
    ```
    clientId=<client-id-of-the-service-principal>
    az role assignment list --assignee ${clientId}
    ```

**Comment by majguo** [comment]
Hello @git4rk Pls close the issue once you assign `User Access Administrator` role to the service principal specified in GitHub Action secret `AZURE_CREDENTIALS` per instructions above.

**Comment by git4rk** [comment]
$ az role assignment list --assignee  `clientId`
```json
[
  {
    "canDelegate": null,
    "condition": null,
    "conditionVersion": null,
    "description": null,
    ...
    "principalName": "http://20210512_IBM_SP",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/...",
    "roleDefinitionName": "Contributor",
    "scope": "/subscriptions/...",
    "type": "Microsoft.Authorization/roleAssignments"
  },
  {
    "canDelegate": null,
    "condition": null,
    "conditionVersion": null,
    "description": null,
    ...
    "principalName": "http://20210512_IBM_SP",
    "principalType": "ServicePrincipal",
    "roleDefinitionId": "/subscriptions/...",
    "roleDefinitionName": "User Access Administrator",
    "scope": "/subscriptions/...",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]
```
