### ISSUE TITLE
Change the offering name

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#20]
Change the offering name from:
IBM WebSphere Server ND V9.0.5 Cluster
to:
IBM WebSphere `Application` Server ND V9.0.5 Cluster

![image](https://user-images.githubusercontent.com/24283162/119027267-2602e180-b974-11eb-9ecc-86abd0f78d68.png)

**Comment by git4rk** [comment]
@edburns Please address this issue while creating/updating the cluster offer in partner center.

**Comment by edburns** [comment]
Fixed.  Please close this. @git4rk
