### ISSUE TITLE
VM cost is not shown in $

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#22]
VM cost is not shown in $. Is that due to some setting on my account or in the code?

![image](https://user-images.githubusercontent.com/24283162/119153994-bf3b0200-ba1f-11eb-91a6-63308e635dc6.png)

**Comment by edburns** [comment]
Hello @git4rk , I expect this is due to the locale settings. It is certainly *not* something we can declare in `createUiDefinition`. I suggest you log in to the portal using a private browsing tab and observe the behavior.

**Comment by git4rk** [comment]
@edburns Its interesting that in private browser I see different set of Directories and O do not see `IBM-MSFT-TEAM`
- **private window**
![image](https://user-images.githubusercontent.com/24283162/119179037-72b1ef80-ba3c-11eb-8d0f-c72acc1f14db.png)

- **non-private window**
![image](https://user-images.githubusercontent.com/24283162/119179106-89f0dd00-ba3c-11eb-991b-93efbbeb5410.png)

**Comment by majguo** [comment]
@git4rk Maybe you can re-try with a different browser (e.g., Firefox, Chrome) with locale settings as `en-us`.

**Comment by git4rk** [comment]
@majguo @edburns I am unable to test it since when I tried Safari I do not even see the `IBM-MSFT-Team` directory:
![image](https://user-images.githubusercontent.com/24283162/120952399-ee888900-c718-11eb-98d0-c983db2b3f3b.png)
Not sure what causes this but most of the time this is what I see on Chrome also (even in private mode).

Ed Spring also sees cost displayed in Pound. Could this be a setting controlled by the owner of `IBM-MSFT-Team` directory?

**Comment by majguo** [comment]
> Ed Spring also sees cost displayed in Pound. Could this be a setting controlled by the owner of IBM-MSFT-Team directory?

@git4rk Honestly I don't know if this behavior is controlled by `IBM-MSFT-Team` directory. As it's related to Azure portal instead of something we're able to control in the offer, I suggest you reach out to [Azure Help + support](https://portal.azure.com/?feature.customportal=false#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

**Comment by git4rk** [comment]
I believe the currency is shown in Pound because of `CURRENCY` setting in the [subscription](https://portal.azure.com/#@wasmsft.onmicrosoft.com/resource/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/properties), not controlled by the browser setting:
![image](https://user-images.githubusercontent.com/24283162/121373089-cb262f80-c90c-11eb-9565-1e4887864727.png)

**Comment by git4rk** [comment]
@majguo Thanks for opening the support ticket to get clarification if the currency setting can be changed at the user level or not: https://portal.azure.com/#resource/subscriptions/1970354a-e600-4847-8848-89ea15c7a8c3/providers/microsoft.support/supporttickets/2106110060002626

**Comment by majguo** [comment]
@git4rk The support confirmed that the currency setting **can't** be changed at the user level, see the response from the screenshot below:
![image](https://user-images.githubusercontent.com/10357495/122149140-2ec0d780-ce8e-11eb-93dc-d8dd2dae05e9.png)

**Comment by git4rk** [comment]
@majguo Thanks.
