### ISSUE TITLE
Wrangle GO NO-GO for Build 2021 release

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#23]
GO NO-GO CRITERIA for offer with Preview creation at “May 24, 2021, 12:52:34 PM UTC
Preview creation.”
I suggest we need a GO NO-GO from the following stakeholders before clicking Go live.
@rk
@charters
@Reza Rahman (Microsoft)
@shane-orourke
@Ed Burns (Microsoft)

**Comment by rk** [comment]
@edburns If you review my profile, you'll find out that I'm not a stakeholder.

**Comment by git4rk** [comment]
@edburns I think you meant @git4rk, not `@rk`.
