### ISSUE TITLE
I need to know what version I'm going to get to check the license

### ISSUE THREAD

**Issue by gcharters** [WASdev/azure.websphere-traditional.cluster#24]
When I provisions a tWAS cluster using the Azure marketplace offer, it asks me to accept the terms of the IBM WAS license and the link points me to a list of licenses.  The offer does not tell me which version it is going to provision and therefore I do now know which license to check.

I think either the link needs to point to a specific license or there needs to be an indication as to which version I check.

**Comment by git4rk** [comment]
The ibm.biz short URL will point to specific WAS version license.
