### ISSUE TITLE
Error message is not clear when Number of VMs is 1

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#25]
![image](https://user-images.githubusercontent.com/24283162/119431909-6a2e1300-bce1-11eb-8aa9-531adfa6d36e.png)

**Comment by majguo** [comment]
Good catch. I suggested the following validation message:

- `The lower limit is 2 because this offer cretes a cluster with 1 deployment manager and at least 1 worker node. The upper limit is 5 because this offer uses a single storage account.`

**Comment by edburns** [comment]
I endorse @majguo 's comment https://github.com/WASdev/azure.websphere-traditional.cluster/issues/25#issuecomment-848401260

**Comment by git4rk** [comment]
Thanks @majguo.  Message looks good. Please fix the typo (`cretes` -> `creates`) in the actual message.

Related question: When we implement the feature to "add node to existing cluster", will this limit still apply? So, customer can only have maximum of 4 worker nodes, ever?

**Comment by majguo** [comment]
@git4rk The message is refined by @edburns so the typo you mentioned has already gone in PR #21 .
For your related question, I think this limit doesn't apply any longer, as adding additional node will be a new deployment which can use new storage account.
