### ISSUE TITLE
Resource Group is created without going thru the deploy/create process

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#28]
**Steps to recreate**
- Launch the portal: https://portal.azure.com/#create/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.2021-04-08-twas-cluster-previewcluster
- Use a new Resource group and go through remaining panel
- Do not click "Create". Cancel the deploy
- Resource Group is created without any resource:
![image](https://user-images.githubusercontent.com/24283162/119586259-54c8ef80-bd9a-11eb-9ba2-3eea1630b197.png)

**Expected result**
- Resource Group should be created after "Create" is initiated

**Comment by majguo** [comment]
@git4rk This is not controlled by our offer, instead, it's Azure to create a new resource group if you choose to deploy using a new resource group and completed step "Review + Create". You can try to create other kind of Azure resource to verify.

**Comment by edburns** [comment]
I endorse the explanation from @majguo  in this comment https://github.com/WASdev/azure.websphere-traditional.cluster/issues/28#issuecomment-848396103

**Comment by edburns** [comment]
@git4rk  if you want us to continue to investigate this particular issue, we will take it up with the Portal team.

**Comment by git4rk** [comment]
@edburns @majguo Thanks. I will close this.
