### ISSUE TITLE
Add link to view WebSphere License 

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#3]
License URL: https://www.ibm.com/software/sla/sladb.nsf/searchlis/?searchview&searchorder=4&searchmax=0&query=%225724-H88%22

**Comment by edburns** [comment]
@git4rk can you please assign this to me.

**Comment by edburns** [comment]
We will put a text box in the first page of the UI with a **learn more** link to the aka.ms URL that redirects to the above license URL.

**Comment by git4rk** [comment]
Reopening to get an ibm.biz/ URL
