### ISSUE TITLE
Post MVP-release offer verbiage updates

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#32]
* Alasdair wanted a new image
* Graham had some concerns about the links
* Graham had some concerns about the overview section
* Domain Manager vs. Deployment Manager

https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1338327

**Comment by git4rk** [comment]
@edburns I can not access [this link](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1338327) and request access link is disabled. Can you please grant me access.
![image](https://user-images.githubusercontent.com/24283162/120910515-920c6780-c64d-11eb-9232-4483ade385eb.png)

**Comment by majguo** [comment]
All of required changes have already been rolled out to the t-was cluster offer. @git4rk , pls help close the issue, thanks.
