### ISSUE TITLE
Improve error message for unentitled IBMId

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#35]
This message gets displayed when IBMId is not entitled. We should improve the error message to indicate what it means.
![image](https://user-images.githubusercontent.com/24283162/120910406-c895b280-c64c-11eb-8617-669555838895.png)

**Comment by majguo** [comment]
@git4rk The current error message for the un-entitled IBMid is:
```
The input IBMid account is Unentitled.
```
Pls provide the improved error message. 

Besides, pls notice that only the highlighted text is customizable:
![image](https://user-images.githubusercontent.com/10357495/124441903-c8edae80-ddae-11eb-9af0-6a3a4bc3f757.png)

**Comment by gcharters** [comment]
How about, "The provided IBM ID does not have entitlement to install WebSphere Application Server".  

Couple of questions: 
1. Can this be customized for each image (e.g. WAS ND, IHS)?  The above suggestion only works if we can customize, otherwise we shouldn't mention the product.
2. Minor suggestion and maybe we need a separate issue for it: can we use "IBM ID" (rather than IBMid) consistently as I think this is the correct/official representation?

**Comment by majguo** [comment]
@gcharters Thanks for your quick response.

> Can this be customized for each image (e.g. WAS ND, IHS)? The above suggestion only works if we can customize, otherwise we shouldn't mention the product.

Yes, we can. I assume error message "The provided IBM ID does not have entitlement to install WebSphere Application Server" is tailored for WAS ND. So what's your suggestion about the one for IHS?

> Minor suggestion and maybe we need a separate issue for it: can we use "IBM ID" (rather than IBMid) consistently as I think this is the correct/official representation?

I do like your comment to use consistent wording across product. #84 is opened to track the request.

**Comment by git4rk** [comment]
@majguo Thanks for fixing the message and "IBM ID". 

The message suggests customer to go to
<img width="683" alt="image" src="https://user-images.githubusercontent.com/24283162/124529035-a754ed00-ddd7-11eb-8005-f04c30d28e5d.png">
That doc does not have any information about this specific error. How can we get that updated or point customer to a different doc?

**Comment by majguo** [comment]
@git4rk Yes, that doc is a generic one about how to use Azure Custom Script Extension with Linux VM. I don't think it can be updated for specific scripts executed using the extension, as there could be tons of custom scripts running with the extension. Instead, I'd like to suggest leveraging the error message which is controlled by our script to indicate user what's the appropriate doc he/she can reference.
Cc @edburns .

**Comment by gcharters** [comment]
For an unentitled error, we have some text and a link in #40 which we could modify for this error.  @majguo is that the sort of thing you're looking for?

**Comment by majguo** [comment]
@gcharters Yes, that's the sort of thing I suggested.

**Comment by gcharters** [comment]
@majguo how about:
The provided IBM ID does not have entitlement to install WebSphere Application Server.  Please contact the primary or secondary contacts for your IBM Passport Advantage site to grant you access or follow steps at [IBM eCustomer Care](https://www-112.ibm.com/software/howtobuy/passportadvantage/homepage/ecarec) for further assistance.

**Comment by majguo** [comment]
@gcharters Thanks @gcharters , it looks good to me. However, the hyperlink doesn't work in the plain text error message:
![image](https://user-images.githubusercontent.com/10357495/125246765-cba75100-e324-11eb-9df7-08ae7a20ef32.png)

So I will use the following one instead:

The provided IBM ID does not have entitlement to install WebSphere Application Server. Please contact the primary or secondary contacts for your IBM Passport Advantage site to grant you access or follow steps at IBM eCustomer Care (https://www-112.ibm.com/software/howtobuy/passportadvantage/homepage/ecarec) for further assistance.

**Comment by edburns** [comment]
@git4rk can you please make an ibm.biz redirect link to the above and post it here?

**Comment by git4rk** [comment]
@edburns @majguo @gcharters I created the short URL: https://ibm.biz/IBMidEntitlement for https://www-112.ibm.com/software/howtobuy/passportadvantage/homepage/ecarec

**Comment by edburns** [comment]
@majguo when this change is made, please use this redirect url instead of the longer one.  https://ibm.biz/IBMidEntitlement.
