### ISSUE TITLE
Modify ARM template to stand up VM based on IHS, use as Load Balancer

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#37]
Depends on [gh-image-28](https://github.com/WASdev/azure.websphere-traditional.image/issues/28).

**Comment by edburns** [comment]
* IHS and DMgr will be on separate VMs
* IHS VM will also have Plugin and WCT
* IHS and DMgr will have public IP. Nodes will have private IP
* All the VMs will be in the same network

**Comment by majguo** [comment]
> * IHS and DMgr will have public IP. Nodes will have private IP

I think it's reasonable that both IHS and DMgr have public IP, as IHS provides the access to the deployed application and DMgr provides the access to the admin web console. However, Issue #38 asks for `Make it so only the IHS server has a public IP`, which conflicts with this issue. @edburns & @git4rk Could you pls clarify what's the final requirement?

**Comment by git4rk** [comment]
@majguo IHS and DMgr need to have public IP. @edburns https://github.com/WASdev/azure.websphere-traditional.cluster/issues/38 can be closed.

**Comment by majguo** [comment]
@git4rk My understanding is that IHS, Plugin and WCT don't need entitlement check. Is that correct?

**Comment by git4rk** [comment]
@majguo IHS install also requires IBMId. Please install version 9.0.5 but do not hardcode the specific version. IM will automatically install the latest version.
