### ISSUE TITLE
Make it possible to have <= 20 nodes in the cluster

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#39]
Hello @git4rk can you please define an upper bound for the number of nodes in the cluster?

**Comment by git4rk** [comment]
@edburns User can only select from dropdown or they can also type it in?

**Comment by git4rk** [comment]
@edburns I discussed this with Alasdair. 20 nodes is fine and we should not go above 50.

**Comment by majguo** [comment]
@edburns @git4rk I'll use a slider which seems a better option comparing to dropdown or text box:
![image](https://user-images.githubusercontent.com/10357495/124367605-4d471100-dc8b-11eb-9e57-2cbf6759ae1e.png)

**Comment by git4rk** [comment]
From 2021-07-06 meeting minutes:
- Entitlement check happens in parallel. When tested with 20 nodes it failed with a PPA authentication.  Consider possibility to make one call to check entitlement for all deployments.  Jianguo to continue to investigate.
- Action: Graham Investigate the issues with listAvailablePackages issue on IBM side.  Why it's happening quite frequently and lasting for up to a day.
- Action: anyone interested in providing feed back on the new  UI?
