### ISSUE TITLE
Display the WAS version being installed

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#4]
Currently it only displays 9.0.5:
![image](https://user-images.githubusercontent.com/24283162/110025624-9ac36980-7cfd-11eb-9e23-f2434d89fe46.png)

We should display the version being installed, like 9.0.5.7

**Comment by edburns** [comment]
@git4rk I'd like to push back on this based on my experience in developing the WLS offers.  We found it was best to be as generic as possible with version numbers in partner center text, but we can be as specific as we want with the text in `createUiDefinition.json`.  Please consider this input and re-evaluate whether or not you still want us to be be specific in the Partner Center offer text.

**Comment by git4rk** [comment]
@edburns that sounds good. Should I keep it open for createUiDefinition.json change?

**Comment by edburns** [comment]
Let's leave the version information in the Marketplace offer.  Please close this one @git4rk .
