### ISSUE TITLE
Deploy fails for IBMId with some special chars in password

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#43]
- Cluster deploy is failing with unentitled IBMid.
- 
![image](https://user-images.githubusercontent.com/24283162/122602940-a125e900-d041-11eb-89b1-ac6a31b578a2.png)

- When I check /var/log/cloud-init-was.log on DMgr, this is all I see:
```
[root@dmgr78bf9fVM log]# cat cloud-init-was.log 
Checking at + Fri Jun 18 17:00:49 UTC 2021
Invalid input format.
Uninstalled com.ibm.websphere.ND.v90_9.0.5007.20210301_1241 from the /datadrive/IBM/WebSphere/ND/V9/ directory.
Uninstalled com.ibm.java.jdk.v8_8.0.6026.20210226_0840 from the /datadrive/IBM/WebSphere/ND/V9/ directory.
Unentitled
```

- My IBMid is entitled, since `./imcl listAvailablePackages -cPA -secureStorageFile mycreds | grep 9.0.5008` from my machine works.
- Looks like it is failing at https://github.com/WASdev/azure.websphere-traditional.image/blob/45d28c23c3f1c1b50996df2915be75b8ecfa2445/twas-nd/src/main/scripts/was-check.sh#L28
`if [ ${#ibmIdCredentials[@]} -eq 2 ]; then`

- I have comma (,) as one of the special character in the password

**Comment by majguo** [comment]
Good catch @git4rk. To fix the issue, I think we need to know the rules for IBMid and its password. Can you pls share about the rules?

**Comment by majguo** [comment]
It's interesting that rules for creating the new IBMid and editing the existing IBMid are different:

![pwd rules when editing the exsiting IBMid](https://user-images.githubusercontent.com/10357495/122698301-a1102e00-d279-11eb-8def-0faa29d290e6.png)
![pwd rules when creating new IBMid](https://user-images.githubusercontent.com/10357495/122698304-a2415b00-d279-11eb-9fe6-7eb0d877e27f.png)

However, to fix the issue, I'll use the intersection between them.
