### ISSUE TITLE
Manual configure plugins in an IHS VM with scripts so that IHS can route HTTP requests to tWAS cluster members

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.cluster#48]
Manually configure plugins in the IHS VM with scripts so that IHS can route HTTP requests to tWAS cluster members, given the following topology of VMs (see an [example of setup](https://ibm-cloud.slack.com/archives/G010BB252NA/p1624366629012100) from the Slack channel thread):
* 1 deployment manager
* 2 cluster members
* 1 IHS server with plugins and WCT

Once the manual configuration is done and successful, pls help document all of scripts so that they can be incorporated into deployment script to automatically configure the IHS server.

**Comment by edburns** [comment]
[Slack conversation](https://ibm-cloud.slack.com/archives/G010BB252NA/p1624468232002900?thread_ts=1624366629.012100&cid=G010BB252NA).

**Comment by git4rk** [comment]
@majguo 
**Notes:**
- Script might need to be modified to match the property names, directories, and userid switching
- Add WAS_ND_INSTALL_DIRECTORY property to IHS virtualimage.properties with the same value as DMgr
- I am attaching the scripts here as .txt file, since GitHub does not allow to attach .sh. Please rename them after downloading.

**Here are the steps to configure IHS:**
1. On IHS VM, copy and run `configure_ihs.sh`. This will: 
    - Create PCT response file
    - Call `wctcmd.sh -tool pct` against the response file
    - Copy the output script, configurewebserver1.sh, to WAS_ND_INSTALL_DIRECTORY/bin of DMgr. You can use a different mechanism to copy the file to DMgr.

2. On DMgr VM, copy and run `configure_ihs_on_dmgr.sh`. This will:
    - Run configurewebserver1.sh script
    - Configure ODRLIB: **We are still working in this step but you should be able to test what we have so far.**

3. Both VMs: Remove response file and .sh files because they contain passwords

[configure_ihs_on_dmgr.sh.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6705084/configure_ihs_on_dmgr.sh.txt)
[configure_ihs.sh.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6705085/configure_ihs.sh.txt)

**Comment by majguo** [comment]
Thanks @git4rk for your quick response, it's really helpful. Besides, I've already opened a PR to address the following note you mentioned above:
> Add WAS_ND_INSTALL_DIRECTORY property to IHS virtualimage.properties with the same value as DMgr

@git4rk and @edburns  Pls help review and get it merged. Once it's merged, @edburns could you pls re-run the pipeline of ihs image and update the ihs vm offer in Partner Center? Thanks.

**Comment by majguo** [comment]
From Eric Covener (See details from [IBM Slack thread)](https://ibm-cloud.slack.com/archives/G010BB252NA/p1624488230011000?thread_ts=1624366629.012100&cid=G010BB252NA):

A basic pre-odrlib validation would be:
0. ps -ef|grep httpd on the webserver box shows some processes with -f conf/httpd.conf and others with -f conf/admin.conf in the cmdline
1. bottom of $IHS_INSTALL_DIRECTORY/conf/httpd.conf has text resembling
WebSpherePluginConfig  $PLUGIN_INSTALL_DIRECTORY/conf/webserver1/plugin-cfg.xml
2. Interactively in the WAS admin console, under Servers -> server types->webservers there is a server named "webserver1" and you can start and stop it from there.
3. If you deploy an app, you can select "webserver1" as a target in addition to the cluster
4. if you return to Servers -> server types->webservers->webserver1 you can use the menu there to "generate plugin-cfg.xml", "propagate plugin-cfg.xml", and then stop and start the webserver.
5. $PLUGIN_INSTALL_DIRECTORY/conf/webserver1/plugin-cfg.xml is updated with some details of your application context root
6. your webapp should be reachable from the webserver ip on port 80 (edited)

**Comment by git4rk** [comment]
@majguo In addition to the two scripts provided above, please copy and invoke these after `configure_ihs_on_dmgr.sh` (on DMgr)
- Copy these files to the same location as `configure_ihs_on_dmgr.sh`
- Execute `configure_im.sh <nodename> <wasuser>`. This will use the other two scripts.

[pluginutil.sh.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6712389/pluginutil.sh.txt)
[configure_im.sh.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6712390/configure_im.sh.txt)
[configure_im.py.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6712392/configure_im.py.txt)

**Comment by covener** [comment]
Note that Tom and I had some issues late into the afternoon where some of the oddities in pluginutil.sh seemed to cause him problems (but were OK on my cluster).
We ported out of mixed bash + python on stdin into being just a jython script, so look for an update Friday.

**Comment by git4rk** [comment]
@majguo With regard to [my previous comment](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/48#issuecomment-867992161) and [Eric's comment](https://github.com/WASdev/azure.websphere-traditional.cluster/issues/48#issuecomment-868122020):
- There is an update to configure_im.sh. Also, it needs `PROFILE_ROOT` variable to be set. This variable is currently not set in virtualimages.properties. So, either it needs to be set there or passed in as a parameter (the default value set in the script will not work in your env)
- A new script is added, pluginutil.py.

[configure_im.sh.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6728228/configure_im.sh.txt)
[pluginutil.py.txt](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6728229/pluginutil.py.txt)

**Comment by majguo** [comment]
@git4rk Based on scripts uploaded to this issue and the necessary tweak, I'm able to configure IHS successfully and make it work to route HTTP client request to cluster members. You can close it if no other comments.
