### ISSUE TITLE
Make image CIS Benchmark compliant

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#49]
@majguo @edburns 
What will it take to make the image CIS benchmark compliant: https://www.cisecurity.org/cis-benchmarks/cis-benchmarks-faq/ ?

**Comment by git4rk** [comment]
I tried to use [CIS Red Hat Enterprise Linux 8 Benchmark L1](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/center-for-internet-security-inc.cis-rhel-8-l1?tab=Overview) in [tWAS Base image](https://github.com/WASdev/azure.websphere-traditional.image/blob/0525c83a69e1a30ea318db4891055d755054e498/config.properties#L20) but the [CI/CD](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/3589173990) failed with this error:

> The specified platform image is not supported for creating a Virtual Machine with unmanaged disks. Please refer to the disallowed VM disk types at https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineimages/get#vmdisktypes.

@majguo When you get a chance, can you please let me know how to resolve this.

**Comment by majguo** [comment]
Related issue: https://github.com/WASdev/azure.websphere-traditional.image/issues/64

**Comment by majguo** [comment]
> @majguo When you get a chance, can you please let me know how to resolve this.

@git4rk I'll investigate it in this sprint. Cc @edburns.

**Comment by majguo** [comment]
@git4rk Today I made progress by successfully deploying a VM using [CIS Red Hat Enterprise Linux 8 Benchmark L1](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/center-for-internet-security-inc.cis-rhel-8-l1?tab=Overview) with managed disks.

**Comment by git4rk** [comment]
https://github.com/WASdev/azure.websphere-traditional.image/issues/64 addressed this issue.
