### ISSUE TITLE
Allow customer to set deployment name

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#6]
Default deployment name is not user friendly:
![image](https://user-images.githubusercontent.com/24283162/110026031-2210dd00-7cfe-11eb-8909-1a979be5fdf7.png)

**Comment by edburns** [comment]
This is not user customizable.  This value comes from what we put in the Partner Center as the **Offer ID**.

**Comment by git4rk** [comment]
Closing as a limitation.
