### ISSUE TITLE
Review the param names, description/help, default values, etc.

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.cluster#7]

**Comment by git4rk** [comment]
@majguo Sure, sounds good. Please remove this issue from the PR. Please attach a word doc to this issue and I will assign this issue to our doc person. Thanks

**Comment by majguo** [comment]
@git4rk Issue removed from the PR. Will work on the word doc containing screenshots for content team review tomorrow.

**Comment by helyarp** [comment]
Hi, here is my ID (doc) review of the Visible and modifiable content of tWAS cluster offer. My comments are suggested changes, not mandatory. I try to simplify and clarify text. 
[vsi_azure_ui_review_comments.docx](https://github.com/WASdev/azure.websphere-traditional.cluster/files/6462544/vsi_azure_ui_review_comments.docx)

**Comment by majguo** [comment]
Hello @helyarp Thanks for your review. I'm just back to work today and will take a look.
