### ISSUE TITLE
Manually create zip bundle containing fix for #43 and upload to Partner Center twas-cluster offer.

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#75]

**Comment by edburns** [comment]
Please assign this to @edburns .

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/123845092-c76d4380-d8e1-11eb-9175-ca9cb1acbf7b.png)

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/123862729-b5e26680-d8f6-11eb-9ab5-de2a29b0e4be.png)

**Comment by edburns** [comment]
[Preview link](https://portal.azure.com/#create/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.2021-04-08-twas-cluster-previewcluster)

**Comment by edburns** [comment]
Hello @majguo , I observe this is still failing with un-entitled.

```
The input IBMid account is Unentitled.
```

I am still investigating.

**Comment by edburns** [comment]
Hello @majguo here is the `imageReference` from the version with the preview link above:

```json
"imageReference": {
    "publisher": "ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops",
    "offer": "2021-04-27-twas-cluster-base-image",
    "sku": "2021-04-27-twas-cluster-base-image",
    "version": "9.0.20210624"
},
```

This is the latest available version of the base image.

**Comment by edburns** [comment]
Here is the `osProfile`:

```json
                "osProfile": {
                    "computerName": "[if(equals(copyIndex(), 0), variables('name_dmgrVM'), concat(variables('const_managedVMPrefix'), copyIndex()))]",
                    "adminUsername": "[parameters('adminUsername')]",
                    "adminPassword": "[parameters('adminPasswordOrKey')]",
                    "linuxConfiguration": "[if(equals(parameters('authenticationType'), 'password'), json('null'), variables('const_linuxConfiguration'))]",
                    "customData": "[base64(concat(parameters('ibmUserId'), ' ', parameters('ibmUserPwd')))]"
                },
```

**Comment by majguo** [comment]
@edburns I just tried the preview link with your IBMid credential, and it successfully deployed a tWAS cluster without un-entitled error:
![image](https://user-images.githubusercontent.com/10357495/123875587-8ff7a900-d96c-11eb-99ed-17e20562f142.png)

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/123891470-f528ab80-d926-11eb-9064-205e8bfe2a9c.png)

**Comment by edburns** [comment]
![image](https://user-images.githubusercontent.com/75821/124043700-9839fd80-d9d9-11eb-93a5-d3f1b13865c1.png)

**Comment by majguo** [comment]
Looks like it's available now, I used the twas-offer from Azure Portal and successfully created a twas cluster using Ed's IBMid credential which contains a comma, and observed that issue #43 is not reproduced.
