### ISSUE TITLE
Create labels in this issue tracker

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#78]
Hello @git4rk , can you please create labels in this issue tracker for the following kinds of issues

- Partner Center Action.
- Related to base image for `ihs`
- Related to base image for `twas-nd`.
- Related to cluster repo.
This will make it easier for us to identify what kinds of actions we need to take for the issue.

**Comment by git4rk** [comment]
@edburns Created following labels:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/24283162/124049058-b279d880-d9e5-11eb-881b-229f9675f592.png">
