### ISSUE TITLE
Create ibm.biz url for correct support page

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.cluster#79]
fyi, I've received a couple of submission failures this morning:
> Acquisition, Pricing, and Terms
> 100.4.3 Country/Region
> Support Public Azure : All links must lead to appropriate and expected information. Links must lead directly to support pages, home page links are not acceptable. Please update the Support link(s) and resubmit your offer. The expected information was: Helpful resources (at least one of the following must be provided: telephone number(s), email support, chat agents, community forums, or working URL to a support landing page). OR Please update Support Public Azure URL with [https://www.ibm.com/contact/in/en/?lnk=flg] and resubmit your offer.

Hello @charters I have observed that the value we currently have for the support link, now redirects to a non-support page:
```
curl --verbose https://www.ibm.com/developerworks/websphere/support/
*   Trying 23.47.18.183...
> GET /developerworks/websphere/support/ HTTP/2
> Host: www.ibm.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301
< x-powered-by: Express
< location: https://developer.ibm.com/depmodels/cloud/
```
I suggest we create an ibm.biz URL that redirects to the correct place, under our control.  According to bing, perhaps that is:

> https://www.ibm.com/mysupport/s/topic/0TO500000001DQQGA2/websphere-application-server?language=en_US&productId=01t50000004uSki

**Comment by git4rk** [comment]
Created https://ibm.biz/tWASIBMSupport pointing to https://www.ibm.com/mysupport/s/topic/0TO500000001DQQGA2/websphere-application-server?language=en_US&productId=01t50000004uSki

**Comment by edburns** [comment]
Looks great, thanks.
